### ISSUE TITLE
trunk is missing  header it seems

### ISSUE THREAD

**Issue by twongjirad** [larlight/larlite#9]
Compiling ProtoShower...
make[2]: Entering directory '/home/twongjirad/working/larbys/dllee_unified/larlite/UserDev/RecoTool/ShowerReco3D/ProtoShower'
<< checking dependencies >>
ProtoShowerAlgOpenCV.cxx:17:34: fatal error: DataFormat/PiZeroROI.h: No such file or directory
 #include "DataFormat/PiZeroROI.h"

**Comment by drinkingkazu** [comment]
That file is gone on purpose I believe.  
Probably shower code is not updated simply on trunk.

You don’t need recotool for laropencv if that’s what you are looking at.
If that’s the reason then let me know. 
fmwk_update branch of laropencv shouldn’t need recotool at all.

**Comment by twongjirad** [comment]
I see. I'll remove recotool from the build.

**Comment by drinkingkazu** [comment]
recotool should not be a part of by-default build to begin with. Or is it?

**Comment by twongjirad** [comment]
Sorry, I had it as part of the build script in dllee_unified.

**Comment by drinkingkazu** [comment]
got it. I expect it to be updated by @davidc1 or someone in near future. good to know it's not a rush.
thanks!
